local GameSession = require('GameSession')

registerForEvent("onInit", function()
	print("Cyberpunk tuning registered")
	GameSession.Listen(function(state)
		GameSession.PrintState(state)
	end)
	GameSession.OnLoad(function()
		print('Game Session Loaded')
		pcall(function() Game.ModStatPlayer("CarryCapacity", "999") end) --(c)psiberx)
	end)
	GameSession.OnStart(function()
		print('Game Session Started')
		pcall(function() Game.ModStatPlayer("CarryCapacity", "999") end) --(c)psiberx)
	end)
end)
